apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/flux/{{gitops.config.store}}
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
